# Site settings
title: Jared Miller
description: All the projects I have done over the years
sidebar_footer: "© 2025 Jared Miller - Built with Jekyll"

# Leave blank unless your site is at a subpath, like /blog
baseurl: ""

username: jaredmiller219
url: "https://jaredmiller219.github.io"

# Theme settings
theme: jekyll-theme-architect

# Plugins (not needed for Architect, but good practice)
plugins:
  - jekyll-feed

show_downloads: true

# Optional: Markdown settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
